openclarity/apiclarity

backend/go.mod
backend/go.sum
backend/pkg/backend/backend.go
backend/pkg/backend/backend_test.go

related to https://github.com/apiclarity/speculator/pull/5

fix: improve non API classification to handle application/*json media type

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/docker.yml
.github/workflows/release.yaml
.golangci.yml
Dockerfile
Makefile
backend/cmd/backend/main.go
backend/pkg/database/database.go
backend/pkg/version/consts.go

Output example
```
$ kubectl -n apiclarity exec deploy/apiclarity -- ./backend version
Version: latest
Commit: e5bc6fddc7308b15e46cf3c2c6144074ce168210
Build Time: 2021-09-19T06:34:49Z
```

feat: add apiclarity version command and update version details during build

---

README.md

To ensure the rest of the commands succeed.
Signed-off-by: Justin Cohen <jucohen@cisco.com>

docs: Added instruction to clone repo

---

README.md

also, cosmetics: set number of "Restarts" on the `kubectl get pods` output to 0
as our software is absolutely flawless and never restarts 😉
Signed-off-by: Felix Kaechele <fkaechel@cisco.com>

docs: add note about PVCs and StorageClass

---

README.md
backend/go.mod
backend/go.sum
backend/pkg/backend/backend.go
backend/pkg/config/config.go
deployment/apiclarity.yaml

related https://github.com/apiclarity/speculator/pull/10
Initial list of headers taken from:
[The HTTP Request Headers List ](https://flaviocopes.com/http-request-headers/)
[List of Common HTTP Headers | NTT Application Security ](https://www.whitehatsec.com/blog/list-of-http-response-headers/)

feat: add the ability to configure headers to ignore

---

ui/src/layout/Inventory/InventoryDetails/Specs/UploadSpec/index.js

https://github.com/apiclarity/apiclarity/issues/69

remove v3.0 from supported spec to upload

---

plugins/Dockerfile.tyk.v3.2.2
plugins/gateway/tyk/v3.2.2/plugin.go
plugins/gateway/tyk/v3.2.2/plugin_test.go

Fix: https://github.com/apiclarity/apiclarity/issues/73

fix: tyk - add slash to path if not exist

---

plugins/gateway/tyk/v3.2.2/plugin.go

fix: https://github.com/apiclarity/apiclarity/issues/70

fix: tyk empty response

---

plugins/gateway/kong/README.md

https://portshift.atlassian.net/browse/MAN-8162

docs: update kong readme

---

charts/apiclarity/templates/post-install-job-kong.yaml
charts/apiclarity/templates/post-install-job-tyk.yaml
charts/apiclarity/templates/post-install-job-wasm.yaml
charts/apiclarity/values.yaml

Fix https://github.com/apiclarity/apiclarity/issues/113

feat(helm): add proxy configuration for the traffic source post install jobs

---

backend/pkg/modules/internal/traceanalyzer/traceanalyzer.go

Prefer reconstructed spec over provided one.

Fix TraceAnalyzer when only reconstructed spec

---

ui/src/layout/Reviewer/ConfirmationModal/confirmation-modal.scss
ui/src/layout/Reviewer/ConfirmationModal/index.js
ui/src/layout/Reviewer/index.js

- allows a user to select either OASv2 or OASv3 in the reconstructed
spec reviewer.

Reconstructed Spec Version Option

---

backend/pkg/modules/internal/fuzzer/clients/docker.go
backend/pkg/modules/internal/fuzzer/clients/fake.go
backend/pkg/modules/internal/fuzzer/clients/interface.go
backend/pkg/modules/internal/fuzzer/clients/kubernetes.go
backend/pkg/modules/internal/fuzzer/config/config.go
backend/pkg/modules/internal/fuzzer/fuzzer.go
backend/pkg/modules/internal/fuzzer/model/api.go
backend/pkg/modules/internal/fuzzer/model/model.go
backend/pkg/modules/internal/fuzzer/tools/tools.go

- Implement new StartTest() operation
- Implement new start test return format.

[fuzzer] feat: start function with depth parameter

---

ui/src/components/Filter/utils.js

- adds missing alert filter types.

Fix: Alert Filter Error

---

backend/pkg/modules/internal/bfla/bfladetector/authz_model.go
backend/pkg/modules/internal/bfla/bfladetector/bfla_notifier.go
backend/pkg/modules/internal/bfla/bfladetector/learn_and_detect_bfla.go
backend/pkg/modules/internal/bfla/bfladetector/learn_and_detect_bfla_test.go
backend/pkg/modules/internal/bfla/bfladetector/opeanapi_provider.go
backend/pkg/modules/internal/bfla/init.go
backend/pkg/modules/internal/bfla/recovery/state.go
backend/pkg/modules/internal/core/core.go
backend/pkg/modules/internal/core/mocks.gen.go
backend/pkg/modules/internal/core/modules.go
backend/pkg/modules/internal/fuzzer/logging/logging.go
backend/pkg/modules/internal/fuzzer/model/api.go
backend/pkg/modules/internal/fuzzer/model/model.go
backend/pkg/modules/modules.go

Fix BFLA testing
Fix bFLA linting

Aduminuc bfla

---

backend/pkg/modules/internal/bfla/bfladetector/findings.go
backend/pkg/modules/internal/bfla/bfladetector/learn_and_detect_bfla.go
backend/pkg/modules/internal/bfla/bfladetector/learn_and_detect_bfla_test.go
backend/pkg/modules/internal/bfla/init.go
charts/apiclarity/templates/deployment.yaml
charts/apiclarity/values.yaml
ui/src/modules/bfla/BflaApiInventory.js

These changes is to make sure that APIClarity BFLA UI works when deployed alone (without integration with Panoptica)
The assumption is that when deployed alone BFLA_AUTOMATIC_LEARNING_AND_DETECTION is set to true, in this case:
- Learning is started automatically and lasts for a predetermined number of traces
- After enough traces are observed BFLA transitions automatically to detection.

Aduminuc oss bfla fixes

---

ui/src/components/FindingsTable/findings-table.scss
ui/src/components/FindingsTable/index.js
ui/src/components/Table/index.js
ui/src/components/Table/table.scss
ui/src/modules/traceanalyzer/index.js
ui/src/utils/utils.js

- adds a new findings component to handle updated findings response
format from backend.

UI Findings Component

---

README.md
plugins/gateway/kong/README.md
plugins/gateway/tyk/README.md

This PR exclusively attempts to apply minor improvements to some pieces of documentation.
Specifically, it,
* Applies some Markdown lining recommendations (spaces around headers, code fences, etc)
* Fixes a typo
* Proper cases some product names

chore: Documentation edits

---

.gitignore
charts/apiclarity/templates/fuzzer-template-configmap.yaml
charts/apiclarity/values.yaml

Update Fuzzer template to support https
Update Fuzzer to support https

[Fuzzer] tls support

---

backend/pkg/modules/internal/fuzzer/model/api.go

Fill the provided_spec_location field on Fuzzer findings

Fill provided_spec_location field for Fuzzer findings

---

backend/go.mod
backend/go.sum

update following https://github.com/openclarity/speculator/pull/24
main PR https://github.com/openclarity/apiclarity/pull/249

dep: update speculator

---

api3/global/openapi.gen.yaml
api3/global/restapi.gen.go
backend/pkg/modules/internal/bfla/bfladetector/bfla_notifier.go
backend/pkg/modules/internal/bfla/bfladetector/learn_and_detect_bfla.go
backend/pkg/modules/internal/bfla/init.go
backend/pkg/modules/internal/bfla/restapi/openapi.yaml
backend/pkg/modules/internal/bfla/restapi/restapi.gen.go

Aduminuc bfla findings

---

api3/global/openapi.gen.yaml
api3/global/restapi.gen.go
backend/pkg/modules/internal/fuzzer/fuzzer.go
backend/pkg/modules/internal/fuzzer/model/api.go
backend/pkg/modules/internal/fuzzer/restapi/openapi.yaml
backend/pkg/modules/internal/fuzzer/restapi/restapi.gen.go

Additional API to allow to fetch short version of the report for previous tests

fuzzer API to retrieve short report for past tests

---

.golangci.yml
backend/go.mod
backend/go.sum
plugins/gateway/tyk/v3.2.2/go.mod
plugins/taper/go.mod

bump labstack/echo to v4.9.0

---

README.md

This is to update the readme to add the section of external trace sources support

update readme to add the section of external trace sources support

---

backend/go.mod
backend/go.sum

Update speculator to fetch https://github.com/openclarity/speculator/commit/7776596c4b2db6955a736315e1731b4e14e07008

update speculator to v0.3.0

---

plugins/gateway/tyk/README.md
plugins/gateway/tyk/deploy/deploy.sh
plugins/gateway/tyk/deploy/undeploy.sh

Undeployment option for tyk plugin

undeployment option tyk plugin

---

plugins/gateway/kong/README.md
plugins/gateway/kong/deploy/deploy.sh
plugins/gateway/kong/deploy/patch-ingress-remove-annotation.yaml
plugins/gateway/kong/deploy/undeploy.sh

Uninstall  for kong plugin
Updated Readme with uninstall instructions

Undeployment option kong

---

api/server/models/api_info.go
api/swagger.yaml
backend/pkg/database/apiinventory.go
ui/src/layout/Inventory/InventoryTable.js

- Update swagger
- Update APIInfo model
- Update the mapping in ApiInventory to have trace source name

update apiInventory to include traceSource name for API Info
